name: Build with Maven and Do Runtime Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - modern-26.2-compat
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Maven Build
        run: mvn -B clean package --file pom.xml

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: relics-of-cthonia-${{ github.sha }}
          path: 'target/SF_RelicsOfCthonia*.jar'
          if-no-files-found: error

  runtime-test:
    name: Paper 26.2 Runtime Test
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '26.2'
            javaVersion: '25'

    steps:
      - uses: FN-FAL113/minecraft-plugin-runtime-test@v1.1.7
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: relics-of-cthonia-${{ github.sha }}
